import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'services',
        path: '',
        title: 'Services Menu',
        translateKey: 'nav.services.services',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'services.allServices',
                path: '/services',
                title: 'All Services',
                translateKey: 'nav.services.allServices',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'services.addService',
                path: '/add-service',
                title: 'Add Service',
                translateKey: 'nav.services.addService',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'articles',
        path: '',
        title: 'Articles Menu',
        translateKey: 'nav.articles.articles',
        icon: 'articles',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'articles.allArticles',
                path: '/articles',
                title: 'All Articles',
                translateKey: 'nav.articles.allArticles',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'articles.addArticle',
                path: '/add-article',
                title: 'Add Article',
                translateKey: 'nav.services.addArticle',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'testimonials',
        path: '',
        title: 'Testimonials Menu',
        translateKey: 'nav.articles.testimonials',
        icon: 'testimonials',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'testimonials.allTestimonials',
                path: '/testimonials',
                title: 'All Testimonials',
                translateKey: 'nav.testimonials.allTestimonials',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'testimonials.addTestimonial',
                path: '/add-testimonial',
                title: 'Add Testimonial',
                translateKey: 'nav.testimonials.addTestimonial',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'jobs',
        path: '',
        title: 'Jobs Menu',
        translateKey: 'nav.jobs.jobs',
        icon: 'jobs',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'jobs.allJobs',
                path: '/jobs',
                title: 'All Jobs',
                translateKey: 'nav.jobs.allJobs',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'jobs.addJob',
                path: '/add-job',
                title: 'Add Job',
                translateKey: 'nav.jobs.addJob',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'jobs.allJobApplications',
                path: '/job-applications',
                title: 'All Job Applications',
                translateKey: 'nav.jobs.allJobApplications',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'packages',
        path: '',
        title: 'Packages Menu',
        translateKey: 'nav.packages.packages',
        icon: 'packages',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'packages.allPackages',
                path: '/allPackages',
                title: 'All Packages',
                translateKey: 'nav.packages.allPackages',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'packages.addPackageParent',
                path: '/add-package',
                title: 'Add Package',
                translateKey: 'nav.packages.addPackageParent',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            // {
            //     key: 'jobs.allJobApplications',
            //     path: '/job-applications',
            //     title: 'All Job Applications',
            //     translateKey: 'nav.jobs.allJobApplications',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },

    {
        key: 'projects',
        path: '',
        title: 'Projects Menu',
        translateKey: 'nav.projects.projects',
        icon: 'projects',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'projects.allProjects',
                path: '/allProjects',
                title: 'All Projects',
                translateKey: 'nav.projects.allProjects',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'projects.addProject',
                path: '/add-project',
                title: 'Add Project',
                translateKey: 'nav.projects.addProject',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'contactUs',
        path: '',
        title: 'Contact Us Menu',
        translateKey: 'nav.contactUs.contactUs',
        icon: 'contactUs',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'contactUs.allRequests',
                path: '/allRequests',
                title: 'All Requests',
                translateKey: 'nav.contactUs.allRequests',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'systemHeaders',
        path: '',
        title: 'System Headers Menu',
        translateKey: 'nav.systemHeaders.systemHeaders',
        icon: 'system',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'systemHeaders.allHeaders',
                path: '/allHeaders',
                title: 'All Headers',
                translateKey: 'nav.systemHeaders.allHeaders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'systemHeaders.addHeader',
                path: '/add-header',
                title: 'Add Header',
                translateKey: 'nav.systemHeaders.addHeader',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // {
    //     key: 'advertisement',
    //     path: '',
    //     title: 'Advertisement Menu',
    //     translateKey: 'nav.advertisement.advertisement',
    //     icon: 'advertisement',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'advertisement.addAdvertisement',
    //             path: '/add-advertisement',
    //             title: 'Add Advertisement',
    //             translateKey: 'nav.advertisement.addAdvertisement',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
]

export default navigationConfig
